### ISSUE TITLE
Wrong popup offset when Godot window is moved.

### ISSUE THREAD

**Issue by nidhin84** [AniMesuro/rhubarb-lipsync-tp-integration-godot#8] opened 2020-08-06 09:07 UTC
i am using ubuntu 20.04 + godot 3.2.2

nothing happening while Project -> Tools -> rhubarb-lipsync-TPI

I used on ubuntu 18.04 godot3.2.2 , some time not working some time working. 

no idea.

**Comment by AniMesuro** [comment] 2020-08-08 03:15
Weird. I'm not totally sure about the cause but I don't believe this is related to linux though.

I used the plugin on Godot 3.2.2 stable (Windows10 64 bit) and even on 3.2.3 unstable releases it worked as intended. Unfortunately I don't have any Linux distro computer to test this, so if the problem is related to the OS it might prove hard to debug.

I might have a guess though: Do you use Godot from 2 monitor screens, an ultra-wide screen, or use Godot in a not maximized window?
I had a similar problem when I opened the menu option with the Godot window positioned at the lower right of the screen. The plugin popup is created but seems wrongly offseted to the Godot Window position.

Please try to reproduce the error by following:
1. Godot window in a maximized size. (plugin popup should appear in the window center)
2. Godot window in a not maximized size, positioned at lower right of the screen. (plugin popup is off-screen or wrongly offseted)

If it didn't do nothing, please launch Godot from the terminal and provide screenshots of the Console after you click on  _Project -> Tools -> Rhubarb Lipsync TPI_

**Comment by nidhin84** [comment] 2020-08-08 14:16
Thank you for the fast support.

I am using 2 monitors.
the problem occurs when i open the plugin when the Godot window in the second window.

It is ok when the window in primary screen.

**Comment by nidhin84** [comment] 2020-08-08 14:17
Great tool ....... 
thank you .......

**Comment by AniMesuro** [comment] 2020-08-08 18:31
No problem! It seems it was a simple vector math error.

The problem should be fixed now. Unfortunately the changes are too minor for a stable release, but you can download the latest commit of [v1.0.x branch](https://github.com/AniMesuro/rhubarb-lipsync-tp-integration-godot/tree/v1.0.x) or the [current commit](https://github.com/AniMesuro/rhubarb-lipsync-tp-integration-godot/tree/0859ad9b3329ed5a69e05ca325a47d8806ea32cf) as of now.
If the problem continues to occur please say so, otherwise the bug will be assumed fixed and the issue closed.

**Comment by AniMesuro** [comment] 2020-08-14 16:31
Issue assumed fixed.

**Closed by AniMesuro** 2020-08-14 16:31 UTC
